---
latitude: 40.8078
longitude: -73.93765
map_zoom: 12
name: The Park Ave North
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 65 East 129th Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10035'
_hotel_id: THE857
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
